#!/usr/bin/ruby

# ignore -- this is for development, same as require 'vrlib'
require File.exists?("./../../lib/vrlib.rb") ?  "./../../lib/vrlib.rb" : "vrlib"

begin
  require 'caracal'
rescue LoadError
  alert "You must install activerecord gem to use this example.  " +
      "Just enter at command prompt:\n\n<b>gem install caracal</b>"
  exit
end

# from require_all gem:
require_rel 'bin/'

MainApp.new.show_glade()

